### ISSUE TITLE
Help: Cookie  on `refresh` token endpoint

### ISSUE THREAD

**Issue by MacheteBang** [TDMR87/BlazorOAuth#1]
Hello!  I'm looking for a little help.  I am trying to do exactly what you've done in this repo, but there is one piece that I am stumbling on - the refresh token endpoint's [validation of the Cookie](https://github.com/TDMR87/BlazorOAuth/blob/74256ef92a4228661072cc46b8542f9f2bc4d2ba/src/BlazorOAuth.API/Controllers/TokenController.cs#L17).

This makes a ton of sense, **HOWEVER**, for the life of me I cannot find where this cookie is added to the request to the API. I can see the request from the client [calling the API](https://github.com/TDMR87/BlazorOAuth/blob/74256ef92a4228661072cc46b8542f9f2bc4d2ba/src/BlazorOAuth.Client/Services/TokenService.cs#L9), however, that request does not have any authorization associated with it.

So then, I discovered the [TokenDelegationHandler](https://github.com/TDMR87/BlazorOAuth/blob/74256ef92a4228661072cc46b8542f9f2bc4d2ba/src/BlazorOAuth.Client/Services/Http/TokenDelegatingHandler.cs#L9) (new concept to me), but am still unable to understand where the Cookie is added to the request to the back end API.

Would you mind explaining how that works?

**Comment by TDMR87** [comment]
Hi @MacheteBang ,

cookies don't need to be explicitly "added" to requests, because browsers attach them to requests automatically. So when the server has sent you a cookie as a response at some point (during successful sign-in for example), the cookie will automatically be attached to any requests that the client sends to the backend.

Here's how it works in this repo:

1. [Here](https://github.com/TDMR87/BlazorOAuth/blob/74256ef92a4228661072cc46b8542f9f2bc4d2ba/src/BlazorOAuth.API/Controllers/AuthController.cs#L67) in the AuthController, when the user is successfully authenticated and signed in, we attach the refresh token cookie to the response. Note: because the refresh token doesn't need to be sent to the backend on **every** request from the client, we specify the **path** so that it is only sent when we call **/api/token/refresh** endpoint.

2. As you already found out, the [TokenDelegatingHandler](https://github.com/TDMR87/BlazorOAuth/blob/74256ef92a4228661072cc46b8542f9f2bc4d2ba/src/BlazorOAuth.Client/Services/Http/TokenDelegatingHandler.cs#L9) (which is like an interceptor, that executes before the actual request) is responsible for refreshing the token. And because the client is already in possession of a cookie (received during sign-in) and we are calling the **/api/token/refresh** endpoint, the browser attaches the cookie to the request for us.

I hope this made sense. I think it's just because the browser handles attaching the cookies, it might seem like black magic is happening.

**Comment by MacheteBang** [comment]
Thank you SO MUCH!  As I kept researching after my post, I read through [`Set-Cookie`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie) and it started to click.

I 100% appreciate you taking the time out to walk through this. Part of my challenge was trying to test my endpoints via Bruno (Postman/Insomnia) and was totally confused!

Thanks for the clarity!
